name: pre-commit

on:
  pull_request:
    branches:
      - main
      - master

env:
  TERRAFORM_VERSION: 1.3.8
  TFLINT_VERSION: v0.49.0

jobs:
  pre_commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Run pre-commit
      uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
      with:
        terraform-version: ${{ env.TERRAFORM_VERSION }}
        tflint-version: ${{ env.TFLINT_VERSION }}
        args: "--all-files --color always --show-diff-on-failure"
